### ISSUE TITLE
Overlay timer displays wrong value when time remaining is 100+ minutes

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#106]
## Bug Description

When the remaining time until the next hydrate break is 100+ minutes, the overlay timer displays the wrong value.
For example, when the time remaining is 102 minutes and 34 seconds, the overlay will falsely display 02:34.
This is due to the overlay currently only supporting the MM:SS format so it will cut off any minute values > 99.

## Steps to Reproduce

Note: This behavior will not be reproducible until the changes from #65 get merged in.

1. Set hydrate reminder interval to over 99 minutes
2. Run the `::hydrate reset` command
3. Observe that the overlay timer displays the wrong value

## Expected Behavior

The overlay timer should always display the accurate value for the time remaining until the next hydrate break.
As a result, the task for this bugfix is to simply reduce the maximum hydrate interval allowed to 90 minutes.

## Screenshots

![Screen Shot 2021-09-12 at 3 29 36 AM](https://user-images.githubusercontent.com/1442227/132984836-8467a359-5a05-4d65-9041-30dc62c1b756.png)

## Environment

Operating System: macOS Big Sur
RuneLite Version:  1.7.22

## Hacktoberfest Details

I will assign this issue to the first person who comments on this issue.
They will be given 48 hours to create a pull request before I allow others to take on this issue.
All other pull requests will be marked as spam and ignored.

Feel free to ask any clarifying questions or for any help in the comments below.

**Comment by dcechano** [comment]
Where is the text calculated? I notice that the tests regarding output strings do pass.

**Comment by jmakhack** [comment]
@dcechano
The text calculation for this can be found in the getText method of HydrateReminderTimer which is currently in review: https://github.com/jmakhack/hydrate-reminder/pull/107/files

The text will actually show the correct value now, but I would still like the maximum to be reduced to 90 minutes since anything over 100 minutes will cause the text to overflow and not look good. Realistically, no one should have the interval set to this high of a value anyways.

![Screen Shot 2021-09-13 at 3 10 06 PM](https://user-images.githubusercontent.com/1442227/133164738-6a8d7194-12b1-48ee-a48d-b52a6f9c2fec.png)

**Comment by LiorBitton** [comment]
Hey @jmakhack , I solved the issue but did not build the java project
