### ISSUE TITLE
Bump RuneLite version

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#114]
## Task Context

A new patch version has been released for `RuneLite` which needs to be reflected in this project in order to accurately test new enhancements and bugfixes.
Bump the RuneLite version in `build.gradle` to match the latest release version as specified on [RuneLite.net](https://runelite.net/).

## Hacktoberfest Details

I will assign this issue to the first person who comments on this issue.
They will be given 48 hours to create a pull request before I allow others to take on this issue.
All other pull requests will be marked as spam and ignored.

This issue will only be assigned to those participating in the ongoing Hacktoberfest event (until it is over).
Each participant will only be allowed to pick up one issue in this project to give others the opportunity to participate as well.

**Comment by NeboCode** [comment]
Hey, please assign this to me, thank you.
