### ISSUE TITLE
Fix label display for overlay timer image configuration option

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#137]
## Bug Description

In the hydrate reminder configuration options, the timer overlay display image drop-down selector does not have a label so the user has no indication of what the drop-down options are for.

## Steps to Reproduce

1. Open the configuration options for the hydrate reminder plugin
2. See under the Timer Overlay Display options that the image drop-down menu does not have a label

## Expected Behavior

There should be a label for the overlay image drop-down menu (similar to `Text Color` and `Timer Display` seen in the screenshot below). In the code, the label is currently set to `Timer Image` but shorter labels such as `Image` or `Icon` are acceptable.

## Screenshots

![config](https://user-images.githubusercontent.com/1442227/177040507-574c93fb-1425-4f7a-b473-779d72a7684f.png)

## Environment

Operating System: Manjaro Linux x86_64
RuneLite Version: 1.8.24.3

## Additional Context

A solution to fix this issue is to shorten the length of long image names so that the drop-down does not take up the entire width of the configuration panel. Names should be shortened in a way such that they are still accurate in describing the images they represent. 

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by macslowiak** [comment]
I want to work on it :)

**Comment by jmakhack** [comment]
Assigned to you @macslowiak. This one might be a bit tedious to go through so the help is much appreciated.

**Comment by macslowiak** [comment]
@jmakhack I checked it and there are only two solutions for this:
1. That what you mentioned.
2. Add void method with config item. Then it will be something like that: 
```
@ConfigItem(
			keyName = "hydrateReminderOverlayTimerImage",
			name = "Timer Image",
			description = "Sets the background image of the timer display",
			position = 3,
			section = hydrateReminderTimerSection
	)
	default void timerImageTitle(){};

	/**
	 * <p>Allows the player to set the image displayed on the overlay timer
	 * </p>
	 * @return the image to display on the overlay timer
	 * @since 1.2.0
	 */
	@ConfigItem(
			keyName = "hydrateReminderOverlayTimerImage",
			name = "Timer Image",
			description = "Sets the background image of the timer display",
			position = 4,
			section = hydrateReminderTimerSection
	)
	default HydrateReminderTimerImages hydrateReminderOverlayTimerImage()
	{
		return HydrateReminderTimerImages.CUP_OF_WATER_IMAGE;
	}
```
From second approach we have something like this:
![image](https://user-images.githubusercontent.com/94566117/194380202-ded32aaf-c421-442a-97a7-dad470950194.png)


I would rather go with 2nd solution (I know it doesn't look pretty).
Not because it easier but there are some names that is really hard to cut and they can be not really understable.

The component and its with itself can be edited but only in library :( 

I will wait for your decision with which approach we would like to go.

**Comment by jmakhack** [comment]
@macslowiak I like this second approach so I say we go with it 👍
