### ISSUE TITLE
Fix unnecessary removal and creation of overlay timer on every game tick

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#138]
## Task Context

In the `onGameTick` method, logic is applied to remove the currently displayed overlay timer and initialize a new one on every single game tick. This is certainly not ideal from a best practices standpoint due to the unnecessary amounts of re-initialization of the overlay timer.

A much better method of handling this logic is to only remove the overlay timer whenever the enable/disable toggle is turned off and only create the overlay timer whenever the toggle is turned on. The only issue with doing this is that any updates to the text color and timer image will not be applied until the user explicitly disables the timer than re-enables it. Part of the work for this task is to also ensure that any updates to the overlay timer configuration get applied immediately after the user makes a change.

![todooverlay](https://user-images.githubusercontent.com/1442227/177040988-a9730884-9b68-4d1b-8bf1-9753de2e82ac.png)

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by PetraJankurova** [comment]
hi could i work on this please? i already started and have made some progress. thanks

**Comment by jmakhack** [comment]
go for it @PetraJankurova! :)

**Comment by jmakhack** [comment]
Hi @PetraJankurova. Just checking in, are you still working on this issue?

**Comment by PetraJankurova** [comment]
yes !
