### ISSUE TITLE
Add static clock for mocking purposes in unit tests

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#139]
## Task Context

In the unit tests for `src/main/java/com/hydratereminder/HydrateReminderPlugin.java`, there is a test commented out due to the need of a static clock within the class in order to properly mock and override certain timing logic. The work for this task is to implement this such that the unit test within `src/test/java/com/hydratereminder/HydrateReminderPluginTest.java` can then be uncommented and run successfully to further improve the overall code coverage on this project.

![todotesting](https://user-images.githubusercontent.com/1442227/177041310-84993bff-b215-482d-b4c4-27bb7c111d6e.png)

**Comment by goncalo-machado** [comment]
Hello, I am new to open source and would like to work on this issue.
