### ISSUE TITLE
Add a new section header for notification configuration options

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#141]
## Feature Reasoning

Now that the hydrate reminder plugin has a multitude of configuration options, the configuration menu can look a bit overwhelming without proper organization and sectioning of the various options.

## Feature Description

Similarly to the newly added `Overlay Timer Display` section header, add a new section header named `Notification Settings` that includes the `Chat notification`, `Chat type`, and `Computer notification` settings.

To keep the section names consistent, it would be good to also rename the `Overlay Timer Display` section to `Overlay Timer Settings`.

Here is a screenshot for reference of the current configuration menu:
![options](https://user-images.githubusercontent.com/1442227/177125346-593a5bd2-05b8-447e-97d7-85919521cb58.png)

## Possible Alternatives

Any other suggestions of how to best section off and label the hydrate reminder configuration options are welcome for consideration.

## Additional Context

The configuration menu code resides in `src/main/java/com/hydratereminder/HydrateReminderConfig.java`.

**Comment by mslowiak** [comment]
@jmakhack I will work on that as well
