### ISSUE TITLE
Add configurable personalities for the hydrate reminder messages

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#144]
## Feature Reasoning

Not everyone wants to see a random hydration related message every time it is time to take a hydration break. 

## Feature Description

This feature is to add a new drop-down configuration option to the menu that allows users to select from a list of different "personalities" for the reminder messages. For now, implementation work should be done for two personalities: `straightforward` and `fun`. The label for the drop-down menu should be set to `Personality`.

For `straightforward`, the only message that should ever come up is `It's time for a quick hydration break` which is currently the first message in the `HYDRATE_BREAK_TEXT_LIST` ArrayList found within `HydrateReminderPlugin.java`.

For `fun`, all other messages except for that first one should be included. Just like things are currently set up, a random message from the list of messages should be displayed on every interval.

## Possible Alternatives

Since there will likely be more personality types as well as a lot more unique messages added in the future, it would be nice to move the ArrayLists to a separate static class instead of keeping it all defined as various constants within the `HydrateReminderPlugin` class which is beginning to get quite bloated. This is definitely just optional work for this feature though as is by no means required towards the completion of this issue.

## Additional Context

Here is the current list of hydrate reminder messages as defined within `HydrateReminderPlugin.java`:
![text](https://user-images.githubusercontent.com/1442227/177314405-45364664-fd51-4175-a6ec-b24469b1d7e8.png)
Add unit tests where necessary.

**Comment by mslowiak** [comment]
@jmakhack Can I pick this up?

**Comment by jmakhack** [comment]
@mslowiak sure, go for it! :)

**Comment by mslowiak** [comment]
@jmakhack 
I have just a question regarding testing the code in Runescape like shown on this video: https://www.youtube.com/watch?v=-eTTrlFoKPc
So basically building the runelite-client adding there the classes from this plugin repository.

I saw there is a `HydrateReminderTest` that runs the RuneLite, but the plugin is not included on startup. Could you help here?

**Comment by mslowiak** [comment]
@jmakhack 
And one question regarding the position of this option? Where should it be located in the menu?

**Comment by jmakhack** [comment]
@mslowiak This comment I made to help someone get their build working might help you here: https://github.com/jmakhack/hydrate-reminder/issues/145#issuecomment-1184297236. `HydrateReminderTest.java` should startup the client and plugin when run after following those steps.

And yes, the option can be placed anywhere in the configuration menu for now with a dropdown select. The placement in the menu is not too important as this will all be refactored and reordered into categories later on.

**Comment by mslowiak** [comment]
Okay, I had outdated `runeLiteVersion` in gradle file. Thanks!
