### ISSUE TITLE
Add chat command for when the user hydrates between interval

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#145]
## Feature Reasoning

Sometimes a player may opt to take a quick hydrate break before the next reminder comes up. Having a `hydrate` chat command to notify the plugin that hydration has occurred would be nice to have for these instances.

## Feature Description

Add a new chat command `hydrate` which does the two following things:

1. Resets the current hydrate reminder interval
2. Increases the total hydrate counter by 1

The `resetHydrateReminderTimeInterval` and `incrementCurrentSessionHydrationBreaks` methods located within `src/main/java/com/hydratereminder/HydrateReminderPlugin.java` already do these two things so the new chat command should essentially just call these two methods.

## Possible Alternatives

A possible alternative is to just rename the `reset` chat command to `hydrate` and make slight tweaks to it. However, it would be nice to have both commands just in case some users would like to keep using the `reset` command.

## Additional Context

Please add unit tests where necessary. Feel free to ask any questions or for any help in the comments below.

**Comment by jmakhack** [comment]
@Diemarg yes, feel free to start working on this and submit a pull request when ready :)

**Comment by Diemarg** [comment]
Hi @jmakhack , I finished working on this issue and all the unit test work, but is there a way to test it in runelite, I have hit a wall in that aspect.

**Comment by jmakhack** [comment]
Hi @Diemarg, the links @Kh1ng are a good place to start. The steps within https://github.com/runelite/plugin-hub/blob/master/README.md are useful to follow. Step 6 under the `Using the template repository` section is especially important for things to work (adding `-ea` to `VM options`). Also, the file to run is [HydrateReminderTest.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/test/java/com/hydratereminder/HydrateReminderTest.java) which should automatically open runelite with the latest build.

You will also need to download runelite from [runelite.net](https://www.runelite.net) and create an account. After that, make sure that the `runeLiteVersion` within `build.gradle` matches the `Latest release` version on  [runelite.net](https://www.runelite.net).

------

If you're still not able to get this setup after trying some more, I don't mind testing your code for you if you just want to open a pull request. There are also automated actions that will check if all unit tests are passing and notify you if they are failing.
