### ISSUE TITLE
Perform a hydration animation whenever a hydration break is occurring

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#146]
## Feature Reasoning

It would be fun to have an animation played whenever it is time to take a hydration break and also whenever the `hydrate` chat command is used.

## Feature Description

There should be two things done as part of the implementation work for this feature request:
1. Add a new configuration option for enabling/disabling this `Hydrate animation` setting
    - See `com/hydratereminder/HydrateReminderConfig.java`
2. Play the `AnimationID.CONSUMING` animation whenever the `incrementCurrentSessionHydrationBreaks` is called in `com/hydratereminder/HydrateReminderPlugin.java`
    - See `net/runelite/api/AnimationID.java` and https://static.runelite.net/api/runelite-api/net/runelite/api/Actor.html#setAnimation(int)

## Possible Alternatives

There are likely other animations that can be used here and may be better than the `CONSUMING` animation. A separate feature enhancement will be opened to address this by either using the best animation found for hydration or by allowing the user to select from a list of animations.

## Additional Context

Add unit tests where necessary/applicable. Feel free to ask any questions in the comments below.

**Comment by mslowiak** [comment]
hi @jmakhack, I would like to work on this issue

**Comment by jmakhack** [comment]
@mslowiak, it's all yours! Feel free to ask any questions here if needed or just open a pull request when ready.
