### ISSUE TITLE
Add new configuration menu section header for animation settings

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#148]
## Feature Reasoning

With the addition of animation configuration options in this release, they should be sectioned off in the configuration menu for better organization and overall clarity.

## Feature Description

There should be a new section header in the plugin configuration menu for `Animation settings` at the bottom. As of the writing of this feature request, there are no configuration options created for this yet, but at least one will be completed as part of #146. It is fine to create this section header either before or after the work for #146 is completed.

## Possible Alternatives

If `Animation settings` does not sound like a good section header, other alternatives for the naming of the section are definitely acceptable.

## Additional Context

Here is a screenshot of the current status of the plugin configuration menu:
![options](https://user-images.githubusercontent.com/1442227/177474799-35a80213-be54-4a6b-989f-9cedec4f944f.png)

The new section header should look similarly to `Overlay Timer Display` in this screenshot.
The work for this feature request should all be contained within `com/hydratereminder/HydrateReminderConfig.java`.

**Comment by mslowiak** [comment]
@jmakhack I will work on that
