### ISSUE TITLE
Show example computer notification when option is enabled

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#160]
## Feature Reasoning

It is not immediately clear what the Computer Notification option will appear like. It would be nice to have an example notification pop up whenever the option is toggled to enable just to see how the notifications will look like when active.

## Feature Description

Whenever the user toggles on the Computer notification option on the configuration menu, an example notification should be immediately displayed with a message like the following: `This is how hydrate reminder computer notifications will appear.`.

## Possible Alternatives

Any alternatives to the message text are acceptable.

## Additional Context

Here is a screenshot of the configuration menu containing the Computer notification option: 
![image](https://user-images.githubusercontent.com/1442227/181216393-2d81a8d2-c78a-47c6-a3d5-8587c89e9c53.png)

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by Jacoberson** [comment]
@jmakhack can you assign this to me?
