### ISSUE TITLE
Fix "File does not end with a newline." Codacy issue

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#162]
## Task Context
Fix the `File does not end with a newline.` issue reported by the Codacy code style checker.
More details on the issue can be found here: https://app.codacy.com/gh/jmakhack/hydrate-reminder/issues?categoryType=CodeStyle

## Screenshots

![Screenshot_20220727_025733](https://user-images.githubusercontent.com/1442227/181219863-2f9a299a-684a-4fda-ab7a-3cda9980cc8b.png)

**Comment by sohamangoes** [comment]
@jmakhack I'd like to take this up :)

**Comment by jmakhack** [comment]
@sohamangoes go for it!

**Comment by sohamangoes** [comment]
Hey @jmakhack sorry I checked this link too late
https://app.codacy.com/gh/jmakhack/hydrate-reminder/issues

Looks like this is not appearing on the dashboard - I verified `HydrateReminderTest` source file as depicted in the screenshot; 
It appears to have a newline at EOF. Should this issue be closed? I don't see any action on this :) Let me know, thanks!

**Comment by jmakhack** [comment]
@sohamangoes ah yeah, looks like the issue is no longer there. Thanks for confirming this. I'll close this issue.
