### ISSUE TITLE
Improve documentation for building and running code

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#171]
## Task Context

There have been multiple contributors who have reported issues regarding building and running the project code. This task is to make it easier for new contributors to figure out how to properly do this. My current thoughts on improving this are to do the following:

1. Add a Building & Running Code section to the Contributing doc
2. Add a link to this section of the doc as part of the New Issues templates

For reference: 
https://github.com/jmakhack/hydrate-reminder/issues/145#issuecomment-1184297236
https://github.com/jmakhack/hydrate-reminder/issues/144#issuecomment-1200114337

**Comment by mslowiak** [comment]
This is a good one @jmakhack! Would be great to have it in readme <3
