### ISSUE TITLE
Remove references to ::hydrate in favor of ::hr

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#173]
## Feature Reasoning

The original `::hydrate` command is quite lengthy to type out and is generally not recommended over the `::hr` alias which is much easier to type. 

## Feature Description

The goal of this enhancement is to allow the `::hydrate` command to remain functional for legacy purposes, but remove it from any user-facing documentation in favor of `::hr`.

There are three parts to this enhancement:

1. Replace all references of `::hydrate` with `::hr` in the README
2. Replace all references of `::hydrate` with `::hr` in the welcome messages
    - See `HYDRATE_WELCOME_TEXT_LIST` in `HydrateReminderPlugin.java`
3. Remove the reference to `::hydrate` within the help command message
    - See `handleHydrateHelpCommand()` in `HydrateReminderPlugin.java`

Making these changes should still allow the `::hydrate` command to work but remove it from all messages and documentation.

## Additional Context

It is possible that there are more references to `::hydrate` that I have missed. If any more references are found, it would be good to remove/replace them as well.

**Comment by Krishpandya682** [comment]
Hi, I would like to work on this

**Comment by jmakhack** [comment]
@Krishpandya682, it's all yours! :)
Just open a pull request when you're ready.

------

In case you have issues building the code, you can refer to: https://github.com/jmakhack/hydrate-reminder/issues/145#issuecomment-1184297236
