### ISSUE TITLE
Remove welcome text class variable in HydrateReminderPlugin.java

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#177]
## Task Context

As part of #175, the welcome messages were extracted from [HydrateReminderPlugin.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderPlugin.java) into its own dictionary class: [HydrateWelcomeMessageDictionary.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/dictionary/HydrateWelcomeMessageDictionary.java).

As a result, the `HYDRATE_WELCOME_TEXT_LIST` class variable found in [HydrateReminderPlugin.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderPlugin.java) is no longer needed. This task is to simply remove the class variable from [HydrateReminderPlugin.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderPlugin.java) and verify that all unit tests still pass and that the project is able to build properly.

**Comment by FinnPixel** [comment]
Removed the class variable. 
All tests passed, did not encounter any problems.
Please verify my changes :)

**Comment by jmakhack** [comment]
Thanks for contributing, @FinnPixel! I will verify your changes later today.
