### ISSUE TITLE
Use string constant in help message

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#179]
## Task Context

https://github.com/jmakhack/hydrate-reminder/blob/aebf4463468bb377e46ac730816b14b8645df01d/src/main/java/com/hydratereminder/HydrateReminderPlugin.java#L476-L477

In the above code, there is a direct reference to `"::"` which is the command prefix that all chat commands in RuneLite uses. There is a constant defined in HydrateReminderPlugin.java that should be used here: `RUNELITE_COMMAND_PREFIX`.

The goal of this task is essentially to remove `"::"` in favor of `RUNELITE_COMMAND_PREFIX` within the construction of the help message.

**Comment by sohamangoes** [comment]
@jmakhack May I take this up?

**Comment by jmakhack** [comment]
@sohamangoes, yes it's all yours if you're still interested on working on this! :)
