### ISSUE TITLE
Add unit tests for HydrateWelcomeMessageDictionary.java

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#182]
## Task Context

As part of #175, a new class was created: [HydrateWelcomeMessageDictionary.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/dictionary/HydrateWelcomeMessageDictionary.java).

The goal of this issue is to add new unit tests for this new class. The new test class should go in `src/test/java/com/hydratereminder/dictionary` and be named `HydrateWelcomeMessageDictionaryTest.java`.

**Comment by sohamangoes** [comment]
@jmakhack can I work on this?

**Comment by jmakhack** [comment]
Go for it, @sohamangoes! :)
