### ISSUE TITLE
Add new hydrate message personality type: Motivational

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#191]
## Feature Reasoning

With the introduction of personality types for hydration break messages, it would be nice to add more new personality types. One such personality type to add is: `motivational`.

## Feature Description

The purpose of this feature request is to add a new personality type `motivational` to the currently existing personality types available for the hydrate break messages. The new personality type should be made selectable via the personality type dropdown menu in the hydrate reminder configuration menu.

To start off, adding at least 12 new messages should be good and more can be added later.
An example of an motivational message could be something like: `It's time to rejuvinate and refresh the body with water for a better and healthier you`

## Possible Alternatives

If not really motivational, any messages that could be considered inspirational and/or encouraging can be considered OK for this personality type.

## Additional Context

To complete this work, the following two files need to be edited:
- [HydrateReminderPersonalityType.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java)
- [HydrateBreakMessageDictionary.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java)

Looking into these two files should give a clear indication on how to implement this feature, but please do ask any questions in the comments below if needed. Please also add and/or update unit tests where necessary.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by aakash232** [comment]
@jmakhack pls assign this issue :)

**Comment by jmakhack** [comment]
Go for it @aakash232

**Comment by aakash232** [comment]
@jmakhack Pls review PR #236

**Comment by aakash232** [comment]
@jmakhack  is the PR good for merge? PR #236
