### ISSUE TITLE
Add new hydrate message personality type: Hype

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#192]
## Feature Reasoning

With the introduction of personality types for hydration break messages, it would be nice to add more new personality types. One such personality type to add is: `hype`.

## Feature Description

The purpose of this feature request is to add a new personality type `hype` to the currently existing personality types available for the hydrate break messages. The new personality type should be made selectable via the personality type dropdown menu in the hydrate reminder configuration menu.

To start off, adding at least 12 new messages should be good and more can be added later.
An example of a hype message could be something like: `Hydration break time! Let's gooooooooooo`

## Possible Alternatives

If not really hype, any messages that could be considered energetic or excited can be considered OK for this personality type.

## Additional Context

To complete this work, the following two files need to be edited:
- [HydrateReminderPersonalityType.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java)
- [HydrateBreakMessageDictionary.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java)

Looking into these two files should give a clear indication on how to implement this feature, but please do ask any questions in the comments below if needed. Please also add and/or update unit tests where necessary.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by jeslyw** [comment]
Would like to have a go at this!

**Comment by jmakhack** [comment]
@jeslyw, just assigned it to you :)

**Comment by esmerexie** [comment]
Good evening if this task is still open I would love to have at it :)

**Comment by jmakhack** [comment]
@esmerexie, this issue has been already assigned to another contributor.

@jeslyw, are you still looking into this issue?

**Comment by jmakhack** [comment]
@esmerexie Since I haven't heard back from the current assignee, I can open up this task for you to work on. Let me know if you are still interested.

**Comment by Prajwalrayal** [comment]
I would like to contribute to this issue if it's still open

**Comment by jmakhack** [comment]
Sure thing. Go for it @Prajwalrayal! :)
