### ISSUE TITLE
Add new hydrate message personality type: Random

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#200]
## Feature Reasoning

With the introduction of personality types for hydration break messages, it would be nice to have a `random` personality type that essentially chooses a random personality to use for every message for a somewhat "full" or "chaotic" experience.

## Feature Description

The purpose of this feature request is to add a new personality type `random` to the currently existing personality types available for the hydrate break messages. The new personality type should be made selectable via the personality type dropdown menu in the hydrate reminder configuration menu.

It should choose a personality type at random where each personality type has an equal chance of being selected. Afterwards the existing logic to select a specific message for that personality type should be executed.

## Additional Context

As this is not a basic personality type and needs some special logic, it would be good to spend a bit of time working out how to structure the logic appropriately to keep the codebase clean and maintainable. New methods may need to be created to existing classes in order to implement this new feature.

To complete this work, the following two files need to be edited (there may be more as well):
- [HydrateReminderPersonalityType.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java)
- [HydrateBreakMessageDictionary.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java)

Please also add and/or update unit tests where necessary.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by akshatjainei** [comment]
Please assign me for this particular issue

**Comment by akshatjainei** [comment]
Please assign me for this issue

**Comment by akshatjainei** [comment]
I am thinking of generating a random number then I will set a range on number which will point towards different cases , and then generate random message which is already their function . Can I go ahead with this approach?
