### ISSUE TITLE
Cleanup position values of the plugin configuration options

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#205]
## Task Context

Currently the position values of the configuration options in [HydrateReminderConfig.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderConfig.java) are somewhat messy with some options having seemingly random position values.

## Acceptance Criteria / Goals

The goal of this task is to cleanup the values of the positions of the configuration options found within [HydrateReminderConfig.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderConfig.java).

## Additional Notes

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by Jacoberson** [comment]
@jmakhack do you want the ConfigSection/ConfigItems placed in position order in the file?

**Comment by jmakhack** [comment]
Each config option in [HydrateReminderConfig.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderConfig.java) has a position value.

For example, the following two config options currently have the same position value of 7 which is a bit confusing.

```
/**
* <p>Separates the overlay timer settings into its own config section
* </p>
* @since 1.2.0
*/
@ConfigSection(
	name = "Overlay Timer Settings",
	description = "Settings for Hydrate Reminder Overlay Timer",
	position = 7
)
String hydrateReminderTimerSection = "Hydrate Reminder Overlay Timer Settings";

/**
* <p>Separates the animation settings into its own config section
* </p>
* @since 2.0.0
*/
@ConfigSection(
	name = "Animation Settings",
	description = "Settings for Hydrate Reminder Animations",
	position = 7
)
String hydrateReminderAnimationSection = "Hydrate Reminder Animation Settings";
```


This task is to clean up those values so that they are something like the following:
![192171984-3e8f79aa-84b7-4f54-b98c-95714d43ea3b](https://user-images.githubusercontent.com/1442227/192898806-5463781c-baa7-4dd9-a8b1-9243823f492f.png)

**Comment by Jacoberson** [comment]
@jmakhack I know #221 is already assigned, but without me changing the position of Personality Type (keeping it at position 11) and after changing positions of all other items/sections, Personality Type moves to below Computer Notification. Do you want me to leave it at its current position, or should I go ahead and resolve #221 with this issue?

![image](https://user-images.githubusercontent.com/58759808/192904056-d1b5bbd6-4d63-4c6a-85bf-4afeaaca2b95.png)

**Comment by jmakhack** [comment]
@Jacoberson ah I see, just leave it at its current position and #221 can pull in your changes and be handled separately.
