### ISSUE TITLE
Show informative tooltip when mouse is hovered over infobox

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#207]
## Feature Reasoning

When hovering over the hydrate reminder infobox overlay box, it would be nice to see an informative tooltip that indicates what the overlay is for.

## Feature Description

When the mouse cursor is hovered over the hydrate reminder overlay, display a tooltip that says `Time until next hydration break`.

![image](https://user-images.githubusercontent.com/1442227/189523920-e0c17758-e7fe-47c0-a9c7-64dce4934bad.png)

## Additional Context

The infobox class that handles the state and logic of the overlay box can be found within [HydrateReminderTimer.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderTimer.java).

For info on how to set a tooltip on an infobox class, take a look at the following documentation: https://static.runelite.net/api/runelite-client/net/runelite/client/ui/overlay/infobox/InfoBox.html

------

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by macslowiak** [comment]
@jmakhack I want to try to do this :)

**Comment by jmakhack** [comment]
@macslowiak, it's all yours!
