### ISSUE TITLE
Extract chat messages logic to separate class 

### ISSUE THREAD

**Issue by mslowiak** [jmakhack/hydrate-reminder#211]
## Task Context
As a next steps when working on project refactoring, we decided to extract the code that is handling specific commands to separate classes. In order to do that, we need to extract firstly the piece of code that is responsible for sending messages to reuse it in the new handler classes.

## Acceptance Criteria / Goals
- Messaging logic is extracted to dedicated class `ChatMessageSender`
- Actual code base should use the new `ChatMessageSender` class instead of existing methods `sendHydrateEmojiChatMessage` from `HydrateReminderPlugin`
- Solution was tested using unit tests

## Additional Notes
Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack or @mslowiak in the comments below with any questions if needed.

**Comment by macslowiak** [comment]
I would like to work on that issue @jmakhack

**Comment by jmakhack** [comment]
Go for it @macslowiak! :)
