### ISSUE TITLE
Extract hydrate command logic to proper handler

### ISSUE THREAD

**Issue by mslowiak** [jmakhack/hydrate-reminder#213]
## Task Context
As a next steps when working on project refactoring, we decided to extract the code that is handling specific commands to separate classes. 
This task is about extracting current `hydrate` command logic from `HydrateReminderPlugin` class to `HydrateCommandHandler` class.

## Acceptance Criteria / Goals
- `hydrate` command logic is extracted to dedicated class `HydrateCommandHandler`
- `HydrateReminderPlugin::onCommandExecuted` should call `commandDelegate.invokeCommand(commandExecuted)` when the selected command is `hydrate`
- Solution was tested using unit tests

## Additional Notes
Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack or @mslowiak in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by macslowiak** [comment]
Please assign that one to me :)
