### ISSUE TITLE
Move personality type setting into the notification settings section

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#221]
## Feature Reasoning

The personality configuration setting affects the personality type for chat and computer notifications. As such, it should be grouped with those settings in the configuration menu.

## Feature Description

As seen in the screenshot below, the personality type configuration setting appears at the bottom of the configuration menu. This enhancement is to place that setting into the `Notification Settings` section under `Computer notification`.

## Possible Alternatives

This setting may be moved in the future based on the addition of other configuration settings but for now, placing it under `Notification Settings` makes the most sense.

## Additional Context

Here is a screenshot of the current configuration menu:
![image](https://user-images.githubusercontent.com/1442227/192171984-3e8f79aa-84b7-4f54-b98c-95714d43ea3b.png)

To implement this enhancement, look into the configuration menu settings implemented within [HydrateReminderConfig.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderConfig.java).

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by SaranshBaniyal** [comment]
@jmakhack can you please assign this to me? I am a beginner level android developer and have worked in java as well as kotlin

**Comment by jmakhack** [comment]
@SaranshBaniyal, it's all yours! Just open a pull request when you're ready.
Feel free to either ping me on here or preferably on the discord if you have any questions.

**Comment by SaranshBaniyal** [comment]
@jmakhack Sure. Thanks, I'll join the discord community

**Comment by Jacoberson** [comment]
@jmakhack can I work on this?

**Comment by SaranshBaniyal** [comment]
@jmakhack I am facing some issue with gradle version being incompatible. Can you guide me how to proceed on this?

**Comment by jmakhack** [comment]
@Jacoberson, this issue has already been assigned to somebody else.

@SaranshBaniyal, can you possibly post a screenshot of what you're having issues with in the discord so I can see exactly what the issue is?

**Comment by SaranshBaniyal** [comment]
@jmakhack ok I'll put a screenshot on the discord. Thanks

**Comment by SaranshBaniyal** [comment]
@jmakhack I m really sorry for the delay in this issue. I am unable to figure out the codebase. Not sure where exactly are the awt graphics lines of code. Also I am not that well versed in awt. Can you provide some resource. And I understand if you want to reassign this issue to someone else too, as I am unable to deliver

**Comment by jmakhack** [comment]
> @jmakhack I m really sorry for the delay in this issue. I am unable to figure out the codebase. Not sure where exactly are the awt graphics lines of code. Also I am not that well versed in awt. Can you provide some resource. And I understand if you want to reassign this issue to someone else too, as I am unable to deliver

@SaranshBaniyal This codebase doesn't use awt graphics. Are you commenting on the correct project?
The fix for this issue should be to just set the correct value for `section` and `position` in [HydrateReminderConfig.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderConfig.java).

**Comment by SaranshBaniyal** [comment]
@jmakhack I did see an import statement of the awt package in HydrateReminderconfig file.  But thanks for explaining I'll try again

**Comment by jmakhack** [comment]
@SaranshBaniyal Ah you're right, I mistook awt for something else. You shouldn't need to use it for this issue. The key/value pairs within `@ConfigItem` should be the only thing that needs to be edited.

**Comment by SaranshBaniyal** [comment]
@jmakhack ok I'll try

**Comment by SaranshBaniyal** [comment]
@jmakhack thanks for your patience, I have created a PR, please have a look and ping me if any changes are required.

**Comment by SaranshBaniyal** [comment]
Thanks, @jmakhack, for all the help. I had a great time working with you and learning from you
