### ISSUE TITLE
Fix timer display hover tooltip description

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#222]
## Bug Description

The hover tooltip description for the timer display setting in the configuration menu contains a description for the wrong setting.

## Steps to Reproduce

1. Open the hydrate reminder configuration menu
2. Hover the mouse over the Timer Display setting
3. Observe that the wrong setting description is displayed

## Expected Behavior

The hover tooltip description for the timer display setting should display a proper description message describing what the setting does.

## Screenshots

![image](https://user-images.githubusercontent.com/1442227/192172610-5e699a6e-df10-46f3-bfd2-fd41a5d375f7.png)

## Environment

Operating System: Manjaro Linux x86_64
RuneLite Version: 1.8.33.3

## Additional Context

What this checkbox setting does is enables/disables the timer infobox overlay display that appears in the upper left corner of the game client window. To get an idea of what to set the description text to, take a look at the description values for other settings such as `Welcome message`, `Chat notification`, and `Computer notification`.

To implement this bugfix, look into the configuration menu settings implemented within [HydrateReminderConfig.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderConfig.java).

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by ArshErgon** [comment]
hmmm, assign it to me..

**Comment by jmakhack** [comment]
Assigned this issue to you, @ArshErgon! :)

**Comment by ArshErgon** [comment]
hi @jmakhack I've downloaded the `runlite v:1.8.33.3` but when I tried to replicate the error I could not find the `Overlay Timer Settings`, I just download the `runlite` and the repo I havn't touch the codebase. Do I need to login?
![Screenshot from 2022-09-27 19-59-49](https://user-images.githubusercontent.com/40994679/192569729-f334329c-02c6-4e34-bc52-d1388d8e3088.png)

**Comment by jmakhack** [comment]
Hey @ArshErgon, you shouldn't have to login to RuneScape in order to see the plugin. Instead of searching for `overlay timer`, try searching for `hydrate reminder`.

Have you also followed the steps in https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md#setting-up-and-building-the-project? If you'd like more help, I'd recommend joining the [Discord](https://discord.gg/RTgxfFW9mS) where other contributors can help as well.

**Comment by Jacoberson** [comment]
@jmakhack can I work on this?

**Comment by ArshErgon** [comment]
Hey @Jacoberson, I'm actually working on it, I haven't started a PR because I'm contributing to other projects also, And I can't manage the time very well, but I will be starting a PRsoon

**Comment by jmakhack** [comment]
Hi @ArshErgon, just checking in. Are you still working on this issue?
