### ISSUE TITLE
Improve hover tooltip description for animation setting

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#223]
## Feature Reasoning

Just from looking into the configuration settings, it is unclear what the animation setting does. It would be nice to have a good descriptive explanation of what the setting does and is used for.

## Feature Description

This enhancement is to improve the hover tooltip description for the animation configuration setting such that it gives a clear explanation of what it exactly does. See below for additional context.

## Possible Alternatives

Any other means of making this setting more clear in what it does could be acceptable.

## Additional Context

Here is a screenshot of the current description:
![image](https://user-images.githubusercontent.com/1442227/192173107-f1861b80-86ff-4b92-8fbb-c70c1233b02f.png)

For context on what this setting does, it enables/disables a hydration animation that the player character performs every time a hydration interval is complete. 

To implement this enhancement, look into the configuration menu settings implemented within [HydrateReminderConfig.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderConfig.java).

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by Jacoberson** [comment]
@jmakhack I've completed this.
