### ISSUE TITLE
Add automation to set reviewers and assignees on pull requests

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#224]
## Task Context

At the moment, pull request reviewers and assignees have to be set manually either while a pull request is being created or after it has already been created. This adds a bit of unnecessary manual labor that should be able to be easily solved with some level of automation.

## Acceptance Criteria / Goals

Whan a new pull request is opened the two following things should be automated:
1. The assignee is set to the Github user who opened the pull request
2. The reviewer is set to @jmakhack

## Additional Notes

Various options to solve this issue should be researched and looked into. For example, this could potentially be solved simply by updated the existing pull request template. However, if that is not possible, a new Github action may need to be integrated into the cicd for this project.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by Kaushik-Iyer** [comment]
Can I try to work on this?

**Comment by jmakhack** [comment]
Sure thing @Kaushik-Iyer. It's assigned to you now :)

**Comment by Manish5121** [comment]
I don't know how to do it yet but can i try working on this ?

**Comment by jmakhack** [comment]
@Manish5121 This issue is not available as it has already been assigned to somebody else.

**Comment by Manish5121** [comment]
> 

Ohh okk 👍
