### ISSUE TITLE
Add new hydrate message personality type: Wizard

### ISSUE THREAD

**Issue by Akshu-on-github** [jmakhack/hydrate-reminder#262]
## Feature Reasoning
With the introduction of personality types for hydration break messages, it would be nice to add more new personality types. One such personality type to add is: `Wizard`

## Feature Description
The purpose of this feature request is to add a new personality type `wizard` to the currently existing personality types available for the hydrate break messages. The new personality type should be made selectable via the personality type dropdown menu in the hydrate reminder configuration menu.

An example of such message: "What's this? My crystal says... That it's time for a sip of water"

## Possible Alternatives
Messages that are from popular Wizard/Magic based franchises, inspired by dnd adventures and so on

## Additional Context
I've raised this Issue inspired by PR #248 and I would like to contribute something similar

**Comment by mslowiak** [comment]
I think it is a nice extension for our plugin :)

**Comment by jmakhack** [comment]
Hey @Akshu-on-github! This is a great idea to add to the current list of personality types.

Are you planning to work on this issue? If so, I can assign this to you :)

**Comment by Akshu-on-github** [comment]
Yes, please assign this to me - I'd like to work on this!
