### ISSUE TITLE
Remove unused imports in HydrateReminderPlugin.java

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#264]
**Note: This issue is designed to be picked up by first time contributors to this project only. If it is not picked up after ~7 days, it will be opened up for anyone to take.**

## Task Context

The Codacy Static Code Analysis system is reporting five unused import errors coming from `HydrateReminderPlugin.java`. The reported issues can be found at: 

https://app.codacy.com/gh/jmakhack/hydrate-reminder/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjI4MzMiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

## Acceptance Criteria / Goals

The goal of this task is to fix all five unused import issues reported by Codacy.

## Additional Notes

After opening a pull request, the Codacy Static Code Analysis will automatically run. It should report that there are five fixed issues if this task is completed successfully.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by swatichauhan814** [comment]
Hey, Can I work on this? @jmakhack

**Comment by jmakhack** [comment]
Go for it @swatichauhan814! I've assigned it to you.
