### ISSUE TITLE
Add new hydrate personality message type : Santa

### ISSUE THREAD

**Issue by kat-kan** [jmakhack/hydrate-reminder#268]
## Feature Reasoning

With the introduction of personality types for hydration break messages, it would be nice to add more new personality types. I know several personalities were added and I have my own suggestion: Santa :) because most of the people like Christmas and it's nice to think of Christmas even in the middle of the summer

## Feature Description

The purpose of this feature request is to add a new personality type Santa to the currently existing personality types available for the hydrate break messages. The new personality type should be made selectable via the personality type dropdown menu in the hydrate reminder configuration menu.

An example of such message: "Smile and drink some water! Santa's coming to town"

## Possible Alternatives

Messages related to Santa, Christmas, Christmas songs

## Additional Context

I've found your project and liked it a lot, then I noticed #262 and I thought that I could contribute in the same way. But that's okay if you don't want to add more personalities :)

**Comment by jmakhack** [comment]
Hey @kat-kan, this idea sounds good to me! :)
 I've assigned this to you.

**Comment by kat-kan** [comment]
Awesome! :)
