### ISSUE TITLE
Add More HydrateBreakMessageDictionary JUnit Tests

### ISSUE THREAD

**Issue by Jacoberson** [jmakhack/hydrate-reminder#269]
## Task Context
There are currently only two unit tests for [HydrateBreakMessageDictionary.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java) class and several personalities have been added as well as a method that gets a random personality.

## Acceptance Criteria / Goals
The goal of this task is to add additional tests to [HydrateBreakMessageDictionaryTest.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/test/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionaryTest.java) to cover additional personalities and the random method.

## Additional Notes

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by Jacoberson** [comment]
@jmakhack if you accept this issue, I'd like to work on it.

**Comment by jmakhack** [comment]
Looks good. Go for it @Jacoberson :)

**Comment by AbbasSalloum** [comment]
Hello, can i help with this issue?

**Comment by jmakhack** [comment]
@AbbasSalloum This issue has already been assigned and taken.
