### ISSUE TITLE
[First Timers Only] Fix redundant field initializer issues

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#272]
**Note: This issue is designed to be picked up by first time contributors to this project only. If it is not picked up after ~7 days, it will be opened up for anyone to take.**

## Task Context

The Codacy Static Code Analysis system is reporting two performance issue(s) coming from `HydrateReminderPlugin.java`. The reported issue(s) can be found at:

https://app.codacy.com/gh/jmakhack/hydrate-reminder/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJQZXJmb3JtYW5jZSJdfSx7ImlkIjoiTGV2ZWwiLCJ2YWx1ZXMiOltdfSx7ImlkIjoiUGF0dGVybiIsInZhbHVlcyI6WyI1MjEzIl19LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltdfV0=

## Acceptance Criteria / Goals

The goal of this task is to fix the two Redundant Field Initializer issue(s) reported by Codacy.

## Additional Notes

After opening a pull request, the Codacy Static Code Analysis will automatically run. It should report that the fixed issue(s) if this task is completed successfully.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by jmakhack** [comment]
@shams-rf I have already assigned you a separate issue and this is for first time contributors only.

**Comment by NNRepos** [comment]
hey, i would like to be assigned if possible 😄

**Comment by RohitPatel1122** [comment]
Hello, I would like to work on this !

**Comment by jmakhack** [comment]
@NNRepos go for it! I've assigned this to you.
