### ISSUE TITLE
[First Timers Only] Fix null assignment issue

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#273]
**Note: This issue is designed to be picked up by first time contributors to this project only. If it is not picked up after ~7 days, it will be opened up for anyone to take.**

## Task Context

The Codacy Static Code Analysis system is reporting a null assignment issue(s) coming from `ChatMessageSender.java`. The reported issue(s) can be found at:

https://app.codacy.com/gh/jmakhack/hydrate-reminder/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJFcnJvclByb25lIl19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjUzOTgiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

## Acceptance Criteria / Goals

The goal of this task is to fix the null assignment issue(s) reported by Codacy.

## Additional Notes

After opening a pull request, the Codacy Static Code Analysis will automatically run. It should report that the fixed issue(s) if this task is completed successfully.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by pwnb0y** [comment]
Assign me

**Comment by jmakhack** [comment]
Go for it @pwnb0y! I've assigned this issue to you.

**Comment by jmakhack** [comment]
@pwnb0y just checking in, are you still working on this issue?

**Comment by pwnb0y** [comment]
Yes
