### ISSUE TITLE
Fix avoid catching generic exception issue

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#274]
**Note: This issue is designed to be picked up by first time contributors to this project only. If it is not picked up after ~7 days, it will be opened up for anyone to take.**

## Task Context

The Codacy Static Code Analysis system is reporting a avoid catching generic exception issue(s) coming from `HydrateEmojiProvider.java`. The reported issue(s) can be found at:

https://app.codacy.com/gh/jmakhack/hydrate-reminder/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJFcnJvclByb25lIl19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjUyOTEiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

## Acceptance Criteria / Goals

The goal of this task is to fix the  avoid catching generic exception issue(s) reported by Codacy.

## Additional Notes

After opening a pull request, the Codacy Static Code Analysis will automatically run. It should report that the fixed issue(s) if this task is completed successfully.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by sanmay321** [comment]
@jmakhack hey i would like to work on this issue,

**Comment by jivjen** [comment]
Hi @jmakhack 
I've raised a PR for this
https://github.com/jmakhack/hydrate-reminder/pull/287
Could you please help review?

**Comment by jmakhack** [comment]
@sanmay321, this issue is open to first time contributors only.
