### ISSUE TITLE
Update the total chat command to also display the number of hydration breaks taken for all time

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#288]
## Feature Reasoning

It would be neat to see the total number of hydration breaks taken not only for the current RuneLite session but for all time.

## Feature Description

Currently the `::hr total` chat command displays the amount of hydration breaks taking during the current RuneLite session: `Current session: _ hydration breaks`. See screenshots in #97.

This feature is to add a second line to the `::hr total` chat command output that displays the total number of hydration breaks taken across **all** RuneLite sessions: `All time: _ hydration breaks`

Make sure to also add testing where necessary.

## Possible Alternatives

Any method of persisting the total amount of hydration breaks taken is valid for completing this issue. The only exceptions would involve storing the value in a third-party service or online.

## Additional Context

Some initial investigation was done in https://github.com/jmakhack/hydrate-reminder/issues/88#issuecomment-890856569 for this issue. Other RuneLite plugins may be useful to look into to see how they address this type of feature/issue.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by Jacoberson** [comment]
@jmakhack I would like to try this.
