### ISSUE TITLE
[First Timers Only] Fix use utility class issues

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#292]
**Note: This issue is to be picked up by first time contributors to this project only. If it is not picked up after ~7 days, it will be opened up for anyone to take.**

## Task Context

The Codacy Static Code Analysis system is reporting three `Use Utility Class` issues coming from multiple files. The reported issue can be found at:

https://app.codacy.com/gh/jmakhack/hydrate-reminder/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJFcnJvclByb25lIl19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjU0NTciXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

## Acceptance Criteria / Goals

The goal of this task is to fix the issue(s) reported by Codacy.

Please use the lombok method of denoting utility classes: https://www.baeldung.com/java-sonar-hide-implicit-constructor#3-using-lombok-utilityclass

## Additional Notes

After opening a pull request, the Codacy Static Code Analysis will automatically run. It should report that the fixed issue(s) if this task is completed successfully.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by akshat-rawat** [comment]
May I work on this issue?

**Comment by jmakhack** [comment]
go for it @akshat-rawat! :)

**Comment by akshat-rawat** [comment]
Hi @jmakhack, I have fixed the issue and also upgraded the `projectlombok:lombok` dependency if that's an issue I can revert back to previous version.

**Comment by jmakhack** [comment]
@akshat-rawat, thanks for your changes! Upgrading the `lombok` dependency will cause the RuneLite Plugin Hub to refuse the plugin so you'll need to revert it back to the previous version.

**Comment by akshat-rawat** [comment]
here is the new pr for the issue.
