### ISSUE TITLE
[First Timers Only] Fix bean members should serialize issues

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#293]
**Note: This issue is to be picked up by first time contributors to this project only. If it is not picked up after ~7 days, it will be opened up for anyone to take.**

## Task Context

The Codacy Static Code Analysis system is reporting 75 bean members should serialize issues coming from multiple files. The reported issue can be found at:

https://app.codacy.com/gh/jmakhack/hydrate-reminder/issues?step=0&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJFcnJvclByb25lIl19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjUzMDYiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ%3D%3D

## Acceptance Criteria / Goals

The goal of this task is to fix the issue(s) reported by Codacy by making all these fields transient.

## Additional Notes

After opening a pull request, the Codacy Static Code Analysis will automatically run. It should report that the fixed issue(s) if this task is completed successfully.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by manish-singh-bisht** [comment]
Hi @jmakhack  do one has to just add 'transient'?
Please correct me if I am wrong,please assign me this.

**Comment by jmakhack** [comment]
@manish-singh-bisht yes, that is correct. I've assigned this to you now.

**Comment by macslowiak** [comment]
@jmakhack I believe it should be closed :)
