### ISSUE TITLE
Refactor getRandomHydrateBreakMessageForPersonality method

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#294]
## Task Context

Right now, the `getRandomHydrateBreakMessageForPersonality` method relies on a switch statement that needs to be updated with every newly added personality type. Also, every case in the switch statement essentially just calls the same method with a different parameter (except for `RANDOM`). This is not ideal as the code is unnecessarily repetitive.

Codacy also reports this as an issue, specifically a `Cyclomatic Complexity` issue. See:
https://app.codacy.com/gh/jmakhack/hydrate-reminder/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJFcnJvclByb25lIl19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjU0MjgiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

## Acceptance Criteria / Goals

The goal of this task is to refactor the `getRandomHydrateBreakMessageForPersonality` method in `HydrateBreakMessageDictionary.java`.

Instead of relying on an ever growing switch statement, one possible option is to create a mapping of personality types to their respective text lists. With this approach, `getRandomBreakMessage` can just be just be passed the correct parameter from the map (i.e. `getRandomBreakMessage(mapName[personalityType])`).

This is only one possible approach though and any other approach to reduce the repetitiveness and complexity of this method is acceptable.

## Additional Notes

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by suryanshsangwan** [comment]
Please assign this to me

**Comment by jmakhack** [comment]
Ok, it is now assigned to you @suryanshsangwan :)

**Comment by jmakhack** [comment]
Hi @suryanshsangwan. Just checking in, are you still working on this issue?

**Comment by hpa16** [comment]
Hi @jmakhack, I'd like to work on this issue if it's available to pick up.
