### ISSUE TITLE
[First Timers Only] Add assert to shouldReturnNothingWhenIsNotHydrateCommand unit test

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#296]
**Note: This issue is to be picked up by first time contributors to this project only. If it is not picked up after ~7 days, it will be opened up for anyone to take.**

## Task Context

The Codacy Static Code Analysis system is reporting an issue coming from `CommandInvokerTest.java`. The reported issue can be found at:

https://app.codacy.com/gh/jmakhack/hydrate-reminder/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJDb2RlU3R5bGUiXX0seyJpZCI6IkxldmVsIiwidmFsdWVzIjpbXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOlsiNTU3NSJdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbXX1d

## Acceptance Criteria / Goals

The goal of this task is to fix the issue(s) reported by Codacy by making adding an assertion to `shouldReturnNothingWhenIsNotHydrateCommand`.

## Additional Notes

After opening a pull request, the Codacy Static Code Analysis will automatically run. It should report that the fixed issue(s) if this task is completed successfully.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by jmakhack** [comment]
Go for it, @AbbasSalloum!

**Comment by AbbasSalloum** [comment]
Hello, I get that I have to add assert to the test but what are the criteria we want to assert Im not sure

**Comment by jmakhack** [comment]
@AbbasSalloum You can add a check that `commandCreator.createFrom(commandType)` is never called when the invalid command is passed in as a parameter to `invokeCommand`.

**Comment by AbbasSalloum** [comment]
Hello,

Is there an issue with this PR? What action items are left to close this PR?

Please advise.

Cheers

**Comment by jmakhack** [comment]
@AbbasSalloum, there have been comments made on your PR that are waiting to be addressed. Please take a look and make the necessary changes when you have time.

**Comment by AbbasSalloum** [comment]
Hello, 

The comments regarding the PR were addressed 

Regards
