### ISSUE TITLE
Add sound effect configuration setting

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#316]
## Feature Reasoning

Similarly to the animation setting, it would be nice to have another setting to play a sound effect every time it is time to take a hydration break.

## Feature Description

This feature should add a setting very similar to the current hydrate animation setting `hydrate sound effect` which when enabled plays a sound effect every time a hydrate interval is completed.

The following is needed to be done:
- Add a new configuration setting section `Sound Effect Settings`
- Add a new configuration setting checkbox `Hydrate sound effect`
- Play a sound effect (can be any) whenever a hydrate interval is completed
- Play a sound effect (can be any) whenever the hydrate command is used

## Possible Alternatives

Any sound effect is valid for the completion of this ticket. Further research and work is to be done in the future for what sound effects should be used for this feature.

As a bonus nice to have, it would be good to create a new enum as a part of this work: `HydrateReminderSoundEffects`. However, this is not a requirement for the completion of this issue.

## Additional Context

Sound effect id enum for reference: https://static.runelite.net/api/runelite-api/net/runelite/api/SoundEffectID.html

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by ssiidd** [comment]
Hey, can I work on this issue?

**Comment by jmakhack** [comment]
go for it @ssiidd

**Comment by ssiidd** [comment]
Hey @jmakhack, I'm having some issues running the tests. When I run the HydrateReminderTest.java file, it opens up the client to this
<img width="768" alt="Screen Shot 2022-10-20 at 11 05 20 AM" src="https://user-images.githubusercontent.com/14967816/197000732-b7c08d83-fdb4-4cf1-8fbd-28d78c1775d6.png">
which seems correct, but whenever I run the tests, nothing happens and it says 0/0 tests passed. I'm not sure if you've had this issue, or maybe it's a problem with my ide (I'm using vscode currently)? please let me know if you have any ideas.

**Comment by jmakhack** [comment]
Hi @ssiidd, did you follow the steps in https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md#setting-up-and-building-the-project? One of the most common issues setting up is that the `-ea` option wasn't set properly.

Otherwise, `HydrateReminderTest.java` opening the client is correct. I've never tried running the tests in vscode so I'm not sure why it would display `0/0 tests passed`. Maybe try editing one of the tests to fail and see if running the test catches the error.

**Comment by ssiidd** [comment]
Hi @jmakhack, I followed all of those instructions and set up the -ea. One thing I noticed is that the gear icon for the plugin is missing. I'm not sure if that might be part of the issue? 
<img width="245" alt="Screen Shot 2022-10-22 at 12 13 03 PM" src="https://user-images.githubusercontent.com/14967816/197353490-fa687167-a19c-41bf-bf14-942de3bb85a3.png">

**Comment by ssiidd** [comment]
I also tried editing the tests and it didn't change

**Comment by jmakhack** [comment]
Hi @ssiidd, that looks like the plugin hub for downloading plugins. You should not be downloading the hydrate reminder plugin from the plugin hub. It should already be included in the client when you run the project through IntelliJ IDEA.

Make sure to do the following:

1. Remove the v1.1.1 version of the hydrate reminder plugin from your client by clicking `Remove` in the Plugin Hub
2. Run the project and the Hydrate Reminder plugin with the latest changes should appear in the list after clicking the following icon:
<img width="40" alt="Screen Shot 2022-10-22 at 6 08 58 PM" src="https://user-images.githubusercontent.com/1442227/197368389-95503612-722e-4aa2-bab5-9ed1e3f707e6.png">

**Comment by ssiidd** [comment]
Hey @jmakhack, I finally got it working. Could I give this issue another shot if no one else is working on it?

**Comment by jmakhack** [comment]
Yeah sure, go for it @ssiidd :)
