### ISSUE TITLE
Add ability to store persistent values in a JSON file

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#322]
## Task Context

As part of #311, new functionality was added to log the total amount of hydration breaks for a user across multiple sessions. The value is currently stored in `totalHydrationBreaks.log` as a numeric value. The goal for this task is to store the value in a json file instead to allow for new potential fields to be added in the future.

## Acceptance Criteria / Goals

The acceptance criteria for this task is to replace the `totalHydrationBreaks.log` usage with a new json file `HydrationReminderStats.json`.

The json object stored should look something like the following:
```json
{
    "totalHydrateCount": 0
}
```

This will allow for more fields and persistent data to be added in the future as needed.

## Additional Notes

There should be other RuneLite plugins that follow this design as well. They may be a good resource to look into to see how they handle this issue. For example: https://github.com/zenpj/eclectic-jars/blob/master/src/main/java/com/eclectic/EclecticPlugin.java

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by Jacoberson** [comment]
@jmakhack I can do this.
