### ISSUE TITLE
[First Timers Only] Fix list-item-spacing issues in documentation

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#325]
## Task Context

The Codacy Static Code Analysis system is reporting multiple list-item-spacing issue(s). The reported issue(s) can be found at:

https://app.codacy.com/gh/jmakhack/hydrate-reminder/issues?bid=22863237&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6WyJNYXJrZG93biJdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOlsiQ29kZVN0eWxlIl19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjY2MjQiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

## Acceptance Criteria / Goals

The goal of this task is to fix the issue(s) reported by Codacy.

## Additional Notes

After opening a pull request, the Codacy Static Code Analysis will automatically run. It should report that the fixed issue(s) if this task is completed successfully.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by manaslohani** [comment]
Hi, i want to work on this.

**Comment by jmakhack** [comment]
Go for it @manaslohani  :)
