### ISSUE TITLE
[First Timers Only] Fix field naming conventions issues

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#333]
## Task Context

The Codacy Static Code Analysis system is reporting field naming conventions issue(s). The reported issue(s) can be found at:

https://app.codacy.com/gh/jmakhack/hydrate-reminder/issues?bid=22863237&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6WyJKYXZhIl19LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJDb2RlU3R5bGUiXX0seyJpZCI6IkxldmVsIiwidmFsdWVzIjpbXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOlsiODA4MyJdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbXX1d

## Acceptance Criteria / Goals

The goal of this task is to fix the issue(s) reported by Codacy.

## Additional Notes

After opening a pull request, the Codacy Static Code Analysis will automatically run. It should report that the fixed issue(s) if this task is completed successfully.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by A-5ingh** [comment]
Can you please assign this to me?
