### ISSUE TITLE
Refactor command exception classes

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#352]
## Task Context

At the moment, `NotRecognizedCommandException` and `NotSupportedCommandException` both extend `RuntimeException`. However, instead of using the taking advantage of how `RuntimeException` handles error messages, these custom exception classes use a `reason` field. This task is to take better advantage of what `RuntimeException` has builtin to its logic.

## Acceptance Criteria / Goals

Refactor both command exception classes to take advantage of the `message` field of the `RuntimeException` class instead of using the current `reason` field.

See the following `RuntimeException` constructor:
```java
/** Constructs a new runtime exception with the specified detail message.
 * The cause is not initialized, and may subsequently be initialized by a
 * call to {@link #initCause}.
 *
 * @param   message   the detail message. The detail message is saved for
 *          later retrieval by the {@link #getMessage()} method.
 */
public RuntimeException(String message) {
    super(message);
}
```

After making these changes, add simple unit tests for both command exception classes as well.

## Additional Notes

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by ron-huberfeld** [comment]
Hi @jmakhack , can I handle this issue?

**Comment by jmakhack** [comment]
go for it @ron-huberfeld

**Comment by ron-huberfeld** [comment]
Hi @jmakhack 
I'm unable to run the tests.
Where can I find an example?

**Comment by jmakhack** [comment]
@ron-huberfeld If you're able to run the project via the steps in [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md), the tests will run automatically and prevent the program from starting if the tests fail. In IntelliJ IDEA, the green play button by any test file will work as well.

Worst case scenario, if you're not able to run them successfully locally, all the tests are run as part of the automated pull request pipeline checks.

**Comment by ron-huberfeld** [comment]
Hi @jmakhack 
Can you please review?
