### ISSUE TITLE
Parameterize JUnit Tests

### ISSUE THREAD

**Issue by Jacoberson** [jmakhack/hydrate-reminder#364]
## Task Context
Codacy has some issues with the unit tests having more than 1 assert. Most of these errors can be resolved by parameterizing tests such as the test in [HydrateBreakMessageDictionaryTest.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/test/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionaryTest.java)

![image](https://user-images.githubusercontent.com/58759808/196212826-8e53005d-7633-4d25-8f90-dd3beb68e817.png)

## Acceptance Criteria / Goals
Tests that have several assertions (specifically assertEquals) are parameterized

## Additional Notes
Some tests such as shouldSetLastHydrateInstantAfterHydrateResetHasOccurred() in [HydrateReminderPluginTest.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/test/java/com/hydratereminder/HydrateReminderPluginTest.java)  cannot be parameterized as they use assertFalse/assertTrue instead of assertEquals

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by Jacoberson** [comment]
@jmakhack I'd like to do this if you accept it.

**Comment by jmakhack** [comment]
@Jacoberson sounds good to me. Feel free to ignore some of the reported issues if it doesn't make sense to parameterize that particular test or to split it into multiple tests.
