### ISSUE TITLE
[First Timers Only] Update contributors display to show 7 contributors per line

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#371]
## Task Context

Given the increasing amount of contributors on this project, it would be nice to condense down the display of contributors in the README.

## Acceptance Criteria / Goals

Update [.all-contributorsrc](https://github.com/jmakhack/hydrate-reminder/blob/master/.all-contributorsrc) so that the @all-contributors bot will update the number of contributors per line the next time it is run.

## Additional Notes

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by RachitGarg-12** [comment]
@jmakhack i would like to contribute on this issue.

**Comment by jmakhack** [comment]
Go for it @RachitGarg-12

**Comment by bhargav26k** [comment]
I want to contribute on this issue.

**Comment by jmakhack** [comment]
@bhargav26k This issue has already been assigned to another contributor.

**Comment by Vaibhavraj-nath-chauhan** [comment]
Can i contribute to the issue

**Comment by jmakhack** [comment]
@Vaibhavraj-nath-chauhan This issue has already been assigned to another contributor.

**Comment by jmakhack** [comment]
Hi @RachitGarg-12, are you still working on this issue?

**Comment by MrinaliniU** [comment]
@jmakhack as discussed could you please assign this issue to me? I have an open PR for this [here](https://github.com/jmakhack/hydrate-reminder/pull/381). Thank you!
