### ISSUE TITLE
Parameterize testImagesGetID jUnit test

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#388]
## Task Context

Currently the `testImagesGetID` unit test in `HydrateReminderImagesTest.java` only tests the ID retrieval for only one hydrate reminder image.

## Acceptance Criteria / Goals

The goal of this task is to parameterize the unit test to test for multiple hydrate reminder images. 

## Additional Notes

For more info on how to possibly parameterize the test, see: https://www.baeldung.com/parameterized-tests-junit-5

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by danissh20** [comment]
@jmakhack I can grab this  😃

**Comment by jmakhack** [comment]
go for it @danissh20!

**Comment by danissh20** [comment]
@jmakhack Please review https://github.com/jmakhack/hydrate-reminder/pull/391

**Comment by danissh20** [comment]
The other approach I can think of this using the constants in the CSV Source for comparison against the enum

`@CsvSource({`
 `           ItemID.BOTTLED_WATER + ", BOTTLED_WATER_IMAGE"`
 `   })`
