### ISSUE TITLE
Makeing variables more clear

### ISSUE THREAD

**Issue by EmmanuelOlofintuyi** [jmakhack/hydrate-reminder#41]
## Is your feature request related to a problem? Please describe
I might have missed but a feature I would suggest is defining variables more clearly to make it easier for other coders to edit

## Describe the solution you'd like
create a comment above or below your method to state new variable and what it does

## Describe any possible alternatives
A clear and concise description of any alternative solutions.

## Additional context
I am new to github so there might be a document I am missing that would help better understand the code and it's variables. If I am mistaken just let me know.

**Comment by jmakhack** [comment]
Closing this for now as this issue and the corresponding PR has been open for over 2 months now with no new activity.
It can be reopened and revisited when ready.
