### ISSUE TITLE
Text for next and prev commands should not display hours and/or minutes when not needed

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#66]
## Bug Description

Instead of showing `0 hours...`, only show minutes and seconds for `::hydrate next` and `::hydrate prev` commands. Also instead of showing `0 hours 0 minutes...`, only show seconds for the commands. Basically, only show the time units that are needed. When the larger time units are 0, remove all that are unnecessary.

## Steps to Reproduce

1. Set the hydrate reminder interval to a value less than 60 minutes
2. Type in `::hydrate next` into the chatbox
3. Observe that the resulting message will always unnecessarily begin with `0 hours`

## Expected Behavior

Only the time units that need to be shown should be shown. For example `0 hours 0 minutes 30 seconds` should be replaced with just `30 seconds`. However, do note that `1 hour 0 minutes 10 seconds` is okay and minutes should not be removed in this case because a higher order time unit is non-zero (`1 hour`).

## Screenshots

![hydrate_commands](https://user-images.githubusercontent.com/1442227/125620263-f150e21f-c63f-46d9-b39e-1619cdd77356.png)

## Environment

Operating System: macOS Big Sur
RuneLite Version: 1.7.15

**Comment by medkhabt** [comment]
@jmakhack  Hi if i understand correctly, if hours change to "0 hours" at any time, we shouldn't display the hours.
