### ISSUE TITLE
Prev command should not display time when no hydration breaks have been taken yet

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#82]
## Bug Description

When initially logging in and running the `::hydrate prev` command before any hydration breaks have been triggered, the command will display a time since the last hydration break. Since no hydration breaks have been taken yet, it should display a separate message instead.

## Steps to Reproduce

1. Login to OSRS via RuneLite client
2. Before any hydrate reminder intervals have passed, type `::hydrate prev` in the chatbox
3. Observe that `x minutes y seconds since last hydration break.` is displayed despite never having taken a hydration break

## Expected Behavior

The `::hydrate prev` command should display a special message in this circumstance such as `No hydration breaks have been taken yet.`

## Screenshots

![Screen Shot 2021-07-27 at 6 21 58 PM](https://user-images.githubusercontent.com/1442227/127248544-b9e4f88c-7cea-4b1f-8dad-e6157ce9277d.png)

## Environment

Operating System: macOS Big Sur
RuneLite Version: 1.7.16

**Comment by medkhabt** [comment]
@jmakhack 
I'll work on this one.
