### ISSUE TITLE
Project structure refactoring

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#99]
## Task Context
Despite hydrate-reminder being a relatively small project, it's main logic within `HydrateReminderPlugin.java` is well over 600 lines of code in length. As new enhancements are continually being planned for this project, this one class containing all the main logic can easily get out of hand and hard to maintain as time goes on.

As a result, I think this is a good point to start doing some overall refactoring on this project. The logic within `HydrateReminderPlugin.java` should be split out into separate classes in a way that makes logical sense.

For example, all the logic for handling chat commands could be separated out to a `HydrateReminderCommandHandler.java` class. The logic for each command can also be split into separate classes but some thought should be done as to not "over-engineer" the project into a big complicated mess. It's important to keep in mind that **the goal of this refactoring is to create a healthy codebase for easier maintenance and development** as opposed to making things more complicated and difficult.

As I am not primarily a Java developer by trade, any input on project structure and design for this project is greatly appreciated. Looking into how other official and third-party plugins structure their project may provide some good insight as well.

Join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by jmakhack** [comment]
The goal now is to separate out all the methods within `HydrateReminderPlugin.java` into logical classes. The only methods that remain within that class should be the RuneLite based event handlers such as `onGameTick`. All other helper methods should be refactored out of the class into handler, dispatcher, utils, etc. type classes.

The output of this ticket now is not to complete the refactoring of this project, but to finalize on a structure of such classes and then to create a number of issues that can be assigned out to others during the upcoming Hacktoberfest event. Any interfaces/abstract classes should have issues created and be completed before the event starts so that nobody is blocked when working on a refactoring task. 

Here is the current structure of the `/src` directory of the project courtesy of CodeSee:
![image](https://user-images.githubusercontent.com/1442227/183855377-b2da1198-63df-4f39-9a44-9bfac425a5c0.png)

The goal is to get `HydrateReminderPlugin.java` to a blueish color in terms of lines of code. This will be very beneficial for the overall maintainability of the project as that single class is on track to hit 1000+ lines of code given the current project trajectory. This will be nice for separating out the tests as well.

After the project structure has been finalized on and the issues have been created, this issue can be closed. It would be good to link all refactoring issues to this issue just to have a central location to view all related issues. This can also potentially be done by creating a new special tag for such issues.


Note: there are other smaller refactoring tasks that should be done on this project (i.e. the improper use of Optionals and the seemingly unnecessary use of the final keyword). However, these are very minor refactors that can be completed after this major refactoring of project files.

**Comment by jmakhack** [comment]
For reference, here is the current UML class diagram of the project:
![image](https://user-images.githubusercontent.com/1442227/184559136-420d1c36-fbb5-4cb5-9116-1f907a6e34c0.png)

**Comment by mslowiak** [comment]
@jmakhack I prepared some skeleton for the refactoring. Please take a look and share your thoughts.

**Comment by jmakhack** [comment]
Closing this issue for now since a lot of refactoring has already been completed and any future refactoring should be opened as separate issues.
